### ISSUE TITLE
Check robot footprint

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_2d_navigation#13]
@bleibe reported today that he didn't think that the robot's footprint includes the touch screen which protrudes a little beyond the base. Please can someone check whether this is the case and fix it if not?

**Comment by bfalacerda** [comment]
The footprint we are using right now is a squared bounding box of the base: check https://github.com/strands-project/scitos_2d_navigation/blob/master/scitos_move_base_params/costmap_common_params.yaml

For this footprint there's no problem, though if we use a stricter approximation of the real base, we might have to take the touch screen into account

**Comment by ToMadoRe** [comment]
Does this mean that by increasing the footprint the path planner will increase the minimum distance to obstacles? In our tests the robot display is sometimes really close to hitting something and I don't think that this goes well in all possible situations. In order to lower this risk, should we increase the footprint, the inflation_radius or any other parameter?
Yesterday we increased the inflation_radius from 0.55 to 0.62. All went fine except for one situation when students tried to edge the robot aside to a desk where it got stuck (path planner could not find a path). Not sure if this would have happened with the original inflation_radius.

**Comment by bfalacerda** [comment]
By increasing the front of the footprint, the robot will not get its front as close to obstacles as it does right now, so when it rotates the screen will also be further away from the objects it might crash into. I expect this to have less of an impact on navigation than increasing the inflation radius, because we keep the width constant. Another option is playing with the cost of going close to objects, as suggested by @nilsbore in https://github.com/strands-project/autonomous_patrolling/issues/70

**Comment by nilsbore** [comment]
Since @lucasb-eyer updated the footprint, maybe it's time to finally close this? @marc-hanheide

**Comment by lucasb-eyer** [comment]
:+1: I don't think it caused any problems for us during the marathon, it helped.
