### ISSUE TITLE
why is this repository only one package?

### ISSUE THREAD

**Issue by Jailander** [strands-project/scitos_2d_navigation#28]
Hi,
I wanted to include two different nodes that are closely related to 2D navigation (a topological navigation planner and an action server that calls move base without caring for the orientation) in the project and I think that this would be the place for it, but I am not sure, is there any other place for these kind of nodes?.

**Comment by hawesie** [comment]
Because it is very generally useful and shouldn't contain code that goes beyond it's remit: "The scitos_2d_navigation stack holds common configuration options for running the 2D navigation stack on a Scitos A5 robot"

I think your additional nodes should go in a new repository, e.g., strands_navigation.

**Comment by Jailander** [comment]
I previously had them all mixed up in autonomous_patrolling and now I have them scitos_apps but I don’t think that they belong to any of these repositories, should we create strands_navigation then?

**Comment by hawesie** [comment]
I think so.

**Comment by Jailander** [comment]
Can you do it?, I don't have enough permissions

**Comment by hawesie** [comment]
Done. https://github.com/strands-project/strands_navigation

**Comment by Jailander** [comment]
Thank you!
