### ISSUE TITLE
edit launch file

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/scitos_2d_navigation#3]
The nav.launch file should not include the map so it can be included in other packages that use their own map (e.g. autonomous patrolling package). After altering this, the autonomous_patrolling (and others, strands_morse?) launch files should also be edited to include the nav.launch directly

**Comment by hawesie** [comment]
A very good point. Anyone know how the PR2 packages do it?

**Comment by kunzel** [comment]
Should we factor out the individual components as much as possible like I did already for the [amcl.launch](https://github.com/strands-project/scitos_2d_navigation/blob/master/scitos_2d_navigation/launch/amcl.launch)?
I would suggest the following files and packages:
- amcl.launch (scitos_2d_navigation)
- move_base.launch (scitos_2d_navigation)
- scitos_state_publisher.launch (scitos_desciption)
- scitos_2d_nav.launch (scitos_2d_navigation), includes amcl, move_base, scitos_state_publisher

This way we could have very lightweight launch file for just adding a map_server. What do you think?

In general, the scitos_2D_navigation package should not contain any maps in my opinion. The package should allow other groups to use the scitos robot, but of course with their own maps. I'd rather prefer a strands_maps or strands_data repository instead.

**Comment by nilsbore** [comment]
This sounds like a very good idea. But the state publisher is already in another package, right? If you're not already on it I'll go ahead and make a pull request with the suggested changes apart from the state publisher and the map since those include other packages. The nicest thing would really be if we didn't have a map anywhere and you have to set it as a param somewhere as the maps will always be different. Doesn't seem like there is any way to pass parameters to a launch file though.

My suggestion would be to load the map file as a parameter from the rosparam service through the launch file. In order to use the scitos_2d_navigation, the user would have to set a parameter by the name of scitos_2d_navigation/map or something like that. Seems to be possible:
http://www.ros.org/wiki/roslaunch/XML/rosparam

**Comment by kunzel** [comment]
Yes, the scitos_state_publisher is already in scitos_description. So you can include it right away. I am not working on it at the moment. So please feel free to restructure the files @nilsbore. 

Passing arguments to roslaunch files should be possible according to the documentation ([roslaunch Command-line tools](http://www.ros.org/wiki/roslaunch/Commandline%20Tools) 1.2 Passing args, [`<arg>` tag](http://www.ros.org/wiki/roslaunch/XML/arg)). Maybe we can pass the map.yaml files?

**Comment by nilsbore** [comment]
But I'm not sure we want the state publisher to be included in scitos_2d_nav.launch. I think it should be started at a more basic level. I have created a pull request with the move base and will try to pass the map as a parameter.

**Comment by bfalacerda** [comment]
I was thinking of just adding, in each package that needs a map, a 
current_map folder where we put the map files we want to use in a given 
run, and have the launch file always loading from there. All rosparam 
stuff sounds like a bit of an overkill for what we want (though I'm 
biased towards copy-pasting instead of using the command line)

**Comment by nilsbore** [comment]
I did it as an argument to the launch file now instead. It looks like: roslaunch scitos_2d_navigation scitos_2d_nav.launch map:=(PATH_TO_MAP_FOLDER)/map.yaml.

**Comment by nilsbore** [comment]
@BFALacerda If you think another structure might be more convenient, please go ahead. Otherwise I would consider this closed.

**Comment by nilsbore** [comment]
That is, I'm open for discussions=). Cheers

**Comment by bfalacerda** [comment]
it's ok, it looks good like this
